import type { NextPage } from "next";
import Head from "next/head";
import BasicButton from "../components/buttons/BasicButton";
import { useState } from "react";
import Modal from "../components/modals/Modal";

const Home: NextPage = () => {
  const [openModal, setOpenModal] = useState(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicButton onClick={() => setOpenModal(true)}>Test</BasicButton>
      {openModal && <Modal closeHandler={setOpenModal}>{"Test"}</Modal>}
    </div>
  );
};

export default Home;
