import type { NextPage } from "next";
import Head from "next/head";
import CenteredModal from "../components/modals/CenteredModal";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CenteredModal />
    </div>
  );
};

export default Home;
